### PR TITLE
Use chokidar for watching

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Seems like it's again path problems on windows :)

**Comment by TrySound** [comment]
@gobblejs/core Let's merge this and I'll try to debug in real world.

**Comment by TrySound** [comment]
Unix still fine.

**Comment by fskreuz** [comment]
Will try this on a Windows when I get to one.

**Comment by TrySound** [comment]
I'm windows user too. And I can't figure out how to install node-gyp in my env. :)

**Comment by fskreuz** [comment]
Should be in wiki: https://github.com/gobblejs/gobble/wiki/Troubleshooting

**Comment by TrySound** [comment]
It's deprecated info. Let's just move to chokidar and breathe freely.

**Pull request merged**
