### PR TITLE
Add tests for merge nodes

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
/cc @gobblejs/core 
I need some help to test symlink which doesn't work in windows.

**Comment by TrySound** [comment]
Should we prevent using symlinks or warn when they are used in Windows. In the second case I need some help from *nix users to write tests.

**Comment by evs-chris** [comment]
Are you referring to symlinks in the source? I think it's perfectly valid to hard link a symlink, at least in posix land. A quick test suggests that it is, anyways.

**Comment by TrySound** [comment]
@evs-chris I mean something like [this](https://github.com/gobblejs/gobble/blob/master/src/nodes/Merger.js#L32). Do you mean they are the same thing here?

**Comment by evs-chris** [comment]
Ah yes. In the case that the source has a symlink to a dir, everything should be copied for the reasons mentioned in the comment. But if the symlink is a file, it can probably be safely hard linked in the new target folder. I'd say that finding symlinks in source would probably be fairly rare, and I think that node just has issues _creating_ symlinks on windows. So as long as gobble doesn't try to create a symlink, it should be good. To be clear, hard linking a symlink does not appear to be the same as creating a symlink, since the symlink is more or less a file that can itself be hard linked.

Does that help any? Sorry, I've not had much free time for gobble in the last year or so, so I'm pretty far out of touch with the code.

**Pull request closed without merging**
