### PR TITLE
Better sourcemap handling

### PR DESCRIPTION
**Pull request by Rich-Harris**
See #64... this is all WIP. The `SOURCEMAP_PROCESS_START` and `SOURCEMAP_PROCESS_COMPLETE` event codes depend on an as-yet unreleased version of gobble-cli

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Actually I'll merge this straight in, otherwise this could become a monster. It makes two changes:

* it creates a `.final` directory, copied from the last stage of the build, and writes the flattened sourcemaps to it. This *might* fix #63 though I haven't looked into it yet. Either way it's the correct behaviour
* only `.js` and `.css` files have their sourcemaps flattened. Other file types are assumed not to have sourcemaps. This speeds things up considerably in some cases

**Comment by evs-chris** [comment]
I like the idea of a final directory. It seems like it would pull `serve` and `build` closer together. How do you feel about having a sort of special observer just for the final product?

**Comment by Rich-Harris** [comment]
Always in favour of anything that makes code DRYer. One thing I was thinking about though was that it'd be neat if sourcemaps were flattened 'lazily' when serving, i.e. as soon as the build proper has finished, the live reload signal is sent and the project can be served, then either a) sourcemaps are generated on demand (if the user has disabled 'em, or the browser can't use 'em, no need to make 'em) or b) failing that, they're generated in any case, but a request for them stalls until they're ready. That kind of optimisation could make a real difference to perceived performance, and hence developer sanity, and so I reckon it'd be good to make sure that we can accommodate that sort of thing.

**Comment by Rich-Harris** [comment]
@evs-chris I had a crack at implementing lazy sourcemaps: #71

**Comment by Rich-Harris** [comment]
Should mention: it doesn't need the `.final` directory any more, because when building/watching it can write sourcemaps straight to the destination directory, and when it's serving it doesn't write flattened sourcemaps to disk at all. So there's no need to symlink/copy everything into a final directory between the last transformer and the ultimate destination.

**Pull request merged**
