### PR TITLE
pathwatcher → chokidar

### PR DESCRIPTION
**Pull request by IvanSanchez**
Replace the `pathwatcher` library with `chokidar` (https://github.com/paulmillr/chokidar).

This is due to gobble currently using 100% of my CPU when running (this happens since I upgrade out of node 0.12 to 4.4+, on linux).

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Hmm... have you seen #92?

**Comment by IvanSanchez** [comment]
Ha, that's weird. In my case is totally the opposite, pathwatcher wastes CPU but chokidar just works.

The way I implemented it, any options to the source gobble node are passed to chokidar - maybe that way the user can set options to change behaviour in his/her system and prevent overheating the CPU?

**Comment by IvanSanchez** [comment]
@MartinKolarik Weird - upgrading the gobble dependency on pathwatcher to the latest version seems to fix my problem. Worth another PR, I guess.

**Comment by IvanSanchez** [comment]
Superseded by #107

**Pull request closed without merging**
